apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: gym-fitness
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
    - port: 3001
      targetPort: 3001
