apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-service
  namespace: gym-fitness
  labels:
    app: trainer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer-service
  template:
    metadata:
      labels:
        app: trainer-service
    spec:
      containers:
        - name: trainer-service
          image: trainer-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
