apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service
  namespace: gym-fitness
  labels:
    app: workout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-service
  template:
    metadata:
      labels:
        app: workout-service
    spec:
      containers:
        - name: workout-service
          image: workout-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
